function [data_plot]=interp_data(data)
% This function maps data as a function of angle and receiver position
% [data_plot]=interp_data(data,dip_angle)
% Input data is a vector generated by Gm, all other variables are loaded from
% the function "make_data.mat".

load receiver
load DIPrange
load d_DipX

angle=-DIPrange:DIPrange;
data_plot=zeros(length(angle),length(receiver));

for kk=1:length(data)
    data_plot(d_DipX==kk)=data(kk);
end

for jj=1:length(receiver)
tempo=data_plot(:,jj)~=0;
d_rec=data_plot(tempo,jj);
angle_rec=angle(tempo);
d_interp=interp1(angle_rec,d_rec,angle,'nearest','extrap');
data_plot(:,jj)=d_interp;
end

end