function run_octree_mesh(work_dir,data_dir,topo_file,dx,expan_x,core,parts,argin)
% EM3DTM octree mesh generator 
% Cycles through a list of folders and generate the input file for the UBC
% code create_octree_mesh_td.exe
% 
% INPUTS PARAMETERS
% work_dir: Source location of directories as generated by data_2_folder.m
% dx:       Vector (1x3) containing the minimum cell size [dx dy dz]
% expan_x:  Vector (1x4) containing the maximum expansion distance
%           [Lx Ly Lz Lair]
% core:     Core region depth
% parts:    Number of parts
%
% OUTPUT
% Octree mesh
%
% Author: D Fournier
% Last Update: April 30th, 2014

%% Driver
home_dir = pwd;

cd(work_dir)

obs_list = ls;

nb_obs = size(obs_list,1)-2;

line_range = argin;

switch line_range 
    case 'all'
        
       range = 1:nb_obs;
       
    otherwise
        
        range = str2num(argin);

end


% Cycle through all the DC lines
for oo = range
    
    
    cd (obs_list(oo+2,:))
    

        % Find the Observation and topo file
        file_list = ls;
        
        obs_file={};

        for ii = 1:size(file_list,1)-2;

            look_at = strtrim(file_list(ii+2,:));

            if strcmp(look_at(end-3:end),'.obs')==1

                obs_file=look_at;

            end


        end
            
        if isempty(obs_file)==1
            
            fprintf(['Program could not find the obs file for line ' obs_list(oo+2,:) '\n'])
            fprintf('Make sure that the file has the right format (*.obs)\n')
            cd ..
            break
            
        end
        
        
        % Write Input file
        fid=fopen('TDcreate_mesh.inp','w');

        fprintf(fid,'%8.2f %8.2f %8.2f ! dx, dy, dz\n',dx);
        fprintf(fid,'%8.2f %8.2f %8.2f %8.2f ! Expansion (x,y,z,air)\n',expan_x);
        fprintf(fid,'%8.2f ! core depth\n',core);
        fprintf(fid,'%i ! number of partition\n',parts);
        fprintf(fid,'%s ! observation file\n',obs_file);
        fprintf(fid,'%s\\%s ! topography file\n',data_dir,topo_file);
        fclose(fid);

        dos ('create_octree_mesh_td TDcreate_mesh.inp')
        cd ..
        
    
    
end

cd(home_dir);