function [misfit]=get_misfit(d_obs)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 25-Jun-2012 08:37:02

DELIMITER = ' ';


% Import the file
data=importdata('maginv3d_001.pre', DELIMITER, 3);
d_pred=data.data(:,4);

misfit=norm(d_pred-d_obs);
